### ISSUE TITLE
songrequest

### ISSUE THREAD

**Issue by styler** [StreamElements/ground-control#7]
Is it possible to get a songrequest "On & Off" on the Ground Control please ? ^^
I think it make Ground Control really cpu intensive
https://i.gyazo.com/3432c1419c1a6cccacec168a02f3fcec.png

**Comment by Ian321** [comment]
<img src="https://static-cdn.jtvnw.net/emoticons/v1/129569/4.0">

**Comment by Ian321** [comment]
It's just chromium <img src="https://cdn.frankerfacez.com/emoticon/107715/2">
